"""
Operations engine: the only way a spec changes (hard rule 1 -- the agent
proposes operations, never code).

apply_operations() is pure: it never mutates the spec it is given, and all
keys are generated here. A caller can never supply a key; the operation
models have no key attributes and reject unknown ones. To let one proposal
create something and then use it ("create Member, add a field to Member")
an operation may carry a `ref`, a throwaway alias valid only inside that
one list of operations.

Nothing is ever deleted. Archiving sets a flag; the records and attribute
rows are untouched, and restoring flips the flag back.
"""

import copy
from typing import Annotated, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter, ValidationError

from agentic.spec import (
    FIELD_TYPES, new_entity_key, new_field_key, new_link_key,
    ENTITY_PREFIX, FIELD_PREFIX, LINK_PREFIX,
)
from agentic.validator import validate_spec, OPTION_TYPES

MAX_OPERATIONS_PER_PROPOSAL = 50

FieldType = Literal["text", "long_text", "number", "date", "boolean",
                    "select", "multiselect", "email", "phone"]
Cardinality = Literal["one_to_one", "many_to_one", "one_to_many", "many_to_many"]

REF_PATTERN = r"^[a-z][a-z0-9_]{0,30}$"


class OperationError(Exception):
    def __init__(self, reasons: list[str]):
        self.reasons = reasons
        super().__init__("; ".join(reasons))


class _Op(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)


class CreateEntityType(_Op):
    op: Literal["create_entity_type"]
    label: str
    ref: Optional[str] = Field(default=None, pattern=REF_PATTERN)


class UpdateEntityType(_Op):
    op: Literal["update_entity_type"]
    entity: str
    label: str


class ArchiveEntityType(_Op):
    op: Literal["archive_entity_type"]
    entity: str


class RestoreEntityType(_Op):
    op: Literal["restore_entity_type"]
    entity: str


class AddField(_Op):
    op: Literal["add_field"]
    entity: str
    label: str
    type: FieldType
    options: Optional[list[str]] = None
    required: bool = False
    ref: Optional[str] = Field(default=None, pattern=REF_PATTERN)


class UpdateField(_Op):
    op: Literal["update_field"]
    entity: str
    field: str
    label: Optional[str] = None
    options: Optional[list[str]] = None
    required: Optional[bool] = None


class ChangeFieldType(_Op):
    op: Literal["change_field_type"]
    entity: str
    field: str
    type: FieldType
    options: Optional[list[str]] = None


class ArchiveField(_Op):
    op: Literal["archive_field"]
    entity: str
    field: str


class RestoreField(_Op):
    op: Literal["restore_field"]
    entity: str
    field: str


class AddLink(_Op):
    op: Literal["add_link"]
    label: str
    from_: str = Field(alias="from")
    to: str
    cardinality: Cardinality = "many_to_one"
    ref: Optional[str] = Field(default=None, pattern=REF_PATTERN)


class ArchiveLink(_Op):
    op: Literal["archive_link"]
    link: str


class RestoreLink(_Op):
    op: Literal["restore_link"]
    link: str


Operation = Annotated[
    Union[CreateEntityType, UpdateEntityType, ArchiveEntityType, RestoreEntityType,
          AddField, UpdateField, ChangeFieldType, ArchiveField, RestoreField,
          AddLink, ArchiveLink, RestoreLink],
    Field(discriminator="op"),
]
_ADAPTER = TypeAdapter(Operation)
OPERATION_NAMES = [m.model_fields["op"].annotation.__args__[0] for m in
                   (CreateEntityType, UpdateEntityType, ArchiveEntityType, RestoreEntityType,
                    AddField, UpdateField, ChangeFieldType, ArchiveField, RestoreField,
                    AddLink, ArchiveLink, RestoreLink)]


# ---------- parsing ----------

def _explain(err: dict) -> str:
    loc = [str(p) for p in err["loc"]]
    where = ".".join(p for p in loc if p not in OPERATION_NAMES)
    kind = err["type"]
    if kind == "union_tag_invalid":
        return f"Unsupported operation. Supported operations: {', '.join(OPERATION_NAMES)}"
    if kind == "union_tag_not_found":
        return "Operation has no 'op' field"
    if kind == "literal_error" and where.endswith("type"):
        return f"Unsupported field type (supported: {', '.join(FIELD_TYPES)})"
    if kind == "literal_error" and where.endswith("cardinality"):
        return "Unsupported link cardinality"
    if kind == "extra_forbidden":
        if loc and loc[-1] in ("key", "keys"):
            return "Keys are generated by the server and cannot be supplied"
        return f"'{where}' is not an accepted attribute of this operation"
    if kind == "missing":
        return f"'{where}' is required"
    if kind == "string_pattern_mismatch":
        return f"'{where}' must be lowercase letters, digits or underscores, starting with a letter"
    return f"'{where}': {err['msg']}" if where else err["msg"]


def parse_operation(raw) -> tuple[object | None, list[str]]:
    if isinstance(raw, BaseModel):
        return raw, []
    if not isinstance(raw, dict):
        return None, ["Operation must be a JSON object"]
    try:
        return _ADAPTER.validate_python(raw), []
    except ValidationError as e:
        return None, [_explain(err) for err in e.errors()]


# ---------- applying ----------

class _Aliases:
    def __init__(self):
        self.maps = {"entity": {}, "field": {}, "link": {}}

    def copy(self):
        other = _Aliases()
        other.maps = {k: dict(v) for k, v in self.maps.items()}
        return other

    def define(self, kind: str, ref: Optional[str], key: str):
        if ref is None:
            return
        if ref.startswith((ENTITY_PREFIX, FIELD_PREFIX, LINK_PREFIX)):
            raise OperationError([f"ref '{ref}' looks like a key; keys are generated by the server"])
        if ref in self.maps[kind]:
            raise OperationError([f"ref '{ref}' is used more than once in this proposal"])
        self.maps[kind][ref] = key


def _taken_keys(spec: dict) -> set[str]:
    keys = set()
    for e in spec["entities"]:
        keys.add(e["key"])
        keys.update(f["key"] for f in e["fields"])
    keys.update(l["key"] for l in spec["links"])
    return keys


def _entity(spec, ref, aliases, allow_archived=False) -> dict:
    key = aliases.maps["entity"].get(ref, ref)
    for e in spec["entities"]:
        if e["key"] == key:
            if e["archived"] and not allow_archived:
                raise OperationError([f"Entity type '{e['label']}' is archived; restore it first"])
            return e
    raise OperationError([f"Entity type '{ref}' does not exist"])


def _field(entity, ref, aliases) -> dict:
    key = aliases.maps["field"].get(ref, ref)
    for f in entity["fields"]:
        if f["key"] == key:
            return f
    raise OperationError([f"Field '{ref}' does not exist on '{entity['label']}'"])


def _link(spec, ref, aliases) -> dict:
    key = aliases.maps["link"].get(ref, ref)
    for l in spec["links"]:
        if l["key"] == key:
            return l
    raise OperationError([f"Link '{ref}' does not exist"])


def _clean_options(options):
    return None if options is None else [o.strip() for o in options]


def _apply_one(spec: dict, op, aliases: _Aliases) -> dict:
    """Mutates `spec` (a working copy) and returns what the operation resolved
    to, for the impact check and plain-language summary."""
    name = op.op

    if name == "create_entity_type":
        key = new_entity_key(_taken_keys(spec))
        spec["entities"].append({"key": key, "label": op.label.strip(), "archived": False, "fields": []})
        aliases.define("entity", op.ref, key)
        return {"entity": key, "entity_label": op.label.strip()}

    if name == "update_entity_type":
        e = _entity(spec, op.entity, aliases)
        old = e["label"]
        e["label"] = op.label.strip()
        return {"entity": e["key"], "entity_label": old, "new_label": e["label"]}

    if name == "archive_entity_type":
        e = _entity(spec, op.entity, aliases)
        cascaded = []
        for l in spec["links"]:
            if not l["archived"] and e["key"] in (l["from"], l["to"]):
                l["archived"] = True
                l["archived_by"] = e["key"]
                cascaded.append(l["key"])
        e["archived"] = True
        return {"entity": e["key"], "entity_label": e["label"], "cascaded_links": cascaded}

    if name == "restore_entity_type":
        e = _entity(spec, op.entity, aliases, allow_archived=True)
        if not e["archived"]:
            raise OperationError([f"Entity type '{e['label']}' is not archived"])
        e["archived"] = False
        by_key = {x["key"]: x for x in spec["entities"]}
        restored = []
        for l in spec["links"]:
            if l.get("archived_by") != e["key"]:
                continue
            other = by_key[l["to"] if l["from"] == e["key"] else l["from"]]
            if other["archived"]:
                # The other end is still archived: the link now waits for it.
                l["archived_by"] = other["key"]
            else:
                l["archived"] = False
                l.pop("archived_by", None)
                restored.append(l["key"])
        return {"entity": e["key"], "entity_label": e["label"], "restored_links": restored}

    if name == "add_field":
        e = _entity(spec, op.entity, aliases)
        key = new_field_key(_taken_keys(spec))
        e["fields"].append({"key": key, "label": op.label.strip(), "type": op.type,
                            "options": _clean_options(op.options), "required": op.required,
                            "archived": False})
        aliases.define("field", op.ref, key)
        return {"entity": e["key"], "entity_label": e["label"], "field": key, "field_label": op.label.strip()}

    if name == "update_field":
        if op.label is None and op.options is None and op.required is None:
            raise OperationError(["update_field changes nothing: give a label, options or required"])
        e = _entity(spec, op.entity, aliases)
        f = _field(e, op.field, aliases)
        if f["archived"]:
            raise OperationError([f"Field '{f['label']}' is archived; restore it first"])
        old_label = f["label"]
        if op.label is not None:
            f["label"] = op.label.strip()
        if op.options is not None:
            f["options"] = _clean_options(op.options)
        if op.required is not None:
            f["required"] = op.required
        return {"entity": e["key"], "entity_label": e["label"], "field": f["key"], "field_label": old_label}

    if name == "change_field_type":
        e = _entity(spec, op.entity, aliases)
        f = _field(e, op.field, aliases)
        if f["archived"]:
            raise OperationError([f"Field '{f['label']}' is archived; restore it first"])
        if f["type"] == op.type and op.options is None:
            raise OperationError([f"Field '{f['label']}' is already of type {op.type}"])
        if op.type in OPTION_TYPES:
            options = _clean_options(op.options) if op.options is not None else f.get("options")
        else:
            options = op.options        # validator rejects options on a non-select type
        f["type"] = op.type
        f["options"] = options
        return {"entity": e["key"], "entity_label": e["label"], "field": f["key"], "field_label": f["label"]}

    if name in ("archive_field", "restore_field"):
        e = _entity(spec, op.entity, aliases)
        f = _field(e, op.field, aliases)
        archiving = name == "archive_field"
        if f["archived"] == archiving:
            raise OperationError([f"Field '{f['label']}' is already {'archived' if archiving else 'active'}"])
        f["archived"] = archiving
        return {"entity": e["key"], "entity_label": e["label"], "field": f["key"], "field_label": f["label"]}

    if name == "add_link":
        for end in (op.from_, op.to):
            _entity(spec, end, aliases)         # existence + not archived, with a clear message
        key = new_link_key(_taken_keys(spec))
        from_key = aliases.maps["entity"].get(op.from_, op.from_)
        to_key = aliases.maps["entity"].get(op.to, op.to)
        spec["links"].append({"key": key, "label": op.label.strip(), "from": from_key, "to": to_key,
                              "cardinality": op.cardinality, "archived": False})
        aliases.define("link", op.ref, key)
        return {"link": key, "link_label": op.label.strip(), "from": from_key, "to": to_key}

    if name in ("archive_link", "restore_link"):
        l = _link(spec, op.link, aliases)
        archiving = name == "archive_link"
        if l["archived"] == archiving:
            raise OperationError([f"Link '{l['label']}' is already {'archived' if archiving else 'active'}"])
        l["archived"] = archiving
        l.pop("archived_by", None)      # a manual archive is never a cascade
        return {"link": l["key"], "link_label": l["label"], "from": l["from"], "to": l["to"]}

    raise OperationError([f"Unsupported operation '{name}'"])


def _dump(op) -> dict:
    return op.model_dump(by_alias=True, exclude_none=True)


def apply_each(spec: dict, raw_ops: list) -> dict:
    """Lenient mode, used when building a proposal. Each operation is applied
    to a copy and the whole result is validated; an operation that fails to
    parse, resolve or validate is dropped with its reasons, and the rest
    still go through. The input spec is never mutated.

    Returns {"spec", "applied": [{index, op, resolved, spec_before}],
             "rejected": [{index, op, reasons}]}."""
    current = copy.deepcopy(spec)
    aliases = _Aliases()
    applied, rejected = [], []

    for index, raw in enumerate(raw_ops):
        if index >= MAX_OPERATIONS_PER_PROPOSAL:
            rejected.append({"index": index, "op": raw,
                             "reasons": [f"Too many operations; at most {MAX_OPERATIONS_PER_PROPOSAL} per proposal"]})
            continue
        op, reasons = parse_operation(raw)
        if op is None:
            rejected.append({"index": index, "op": raw, "reasons": reasons})
            continue
        trial = copy.deepcopy(current)
        trial_aliases = aliases.copy()
        try:
            resolved = _apply_one(trial, op, trial_aliases)
            issues = validate_spec(trial)
            if issues:
                raise OperationError(issues)
        except OperationError as e:
            rejected.append({"index": index, "op": _dump(op), "reasons": e.reasons})
            continue
        applied.append({"index": index, "op": _dump(op), "resolved": resolved, "spec_before": current})
        current, aliases = trial, trial_aliases

    return {"spec": current, "applied": applied, "rejected": rejected}


def apply_operations(spec: dict, ops: list) -> dict:
    """Strict mode, used on approve. Returns a new spec with every operation
    applied, or raises OperationError carrying the reasons of the first
    operation that fails. Never mutates `spec`."""
    result = apply_each(spec, ops)
    if result["rejected"]:
        first = result["rejected"][0]
        raise OperationError([f"Operation {first['index'] + 1}: {r}" for r in first["reasons"]])
    return result["spec"]


# ---------- plain-language summary ----------

def describe(op: dict, resolved: dict) -> str:
    name = op["op"]
    ent = resolved.get("entity_label")
    field = resolved.get("field_label")
    if name == "create_entity_type":
        return f'Create entity type "{op["label"].strip()}"'
    if name == "update_entity_type":
        return f'Rename entity type "{ent}" to "{op["label"].strip()}"'
    if name == "archive_entity_type":
        n = len(resolved.get("cascaded_links", []))
        return f'Archive entity type "{ent}"' + (f" and {n} link(s) to it" if n else "") + " (data is kept)"
    if name == "restore_entity_type":
        n = len(resolved.get("restored_links", []))
        return f'Restore entity type "{ent}"' + (f" and {n} link(s)" if n else "")
    if name == "add_field":
        return f'Add {op["type"]} field "{op["label"].strip()}" to "{ent}"'
    if name == "update_field":
        parts = []
        if "label" in op:
            parts.append(f'rename to "{op["label"].strip()}"')
        if "options" in op:
            parts.append("change the options")
        if "required" in op:
            parts.append("make it required" if op["required"] else "make it optional")
        return f'On "{ent}", field "{field}": ' + ", ".join(parts)
    if name == "change_field_type":
        return f'Change field "{field}" on "{ent}" to type {op["type"]}'
    if name == "archive_field":
        return f'Archive field "{field}" on "{ent}" (values are kept)'
    if name == "restore_field":
        return f'Restore field "{field}" on "{ent}"'
    if name == "add_link":
        return f'Add link "{op["label"].strip()}"'
    if name == "archive_link":
        return f'Archive link "{resolved.get("link_label")}"'
    if name == "restore_link":
        return f'Restore link "{resolved.get("link_label")}"'
    return name
